---
- hosts: firewall 
  remote_user: ubuntu
  tasks:

    - name: update package registry
      apt: update_cache=yes 
      become: true  

    - apt: name=daemon
      become: true

    - name: copy snort config
      copy: src=snort.conf dest=/home/ubuntu

    - name: copy run snort.sh
      copy: src=run_snort.sh dest=/home/ubuntu mode=0755

    - name: copy screenrc
      copy: src=firewall-screenrc dest=/home/ubuntu/firewall-screenrc
    
    - name: write gateway IP
      shell: echo {{gateway_ip}} > /home/ubuntu/gateway_ip

    - name: write webserver IP
      shell: echo {{webserver_ip}} > /home/ubuntu/webserver_ip

    - pause: seconds=20

    #- name: start screen
    #  shell: screen -d -m -c /home/ubuntu/firewall-screenrc

    - name: run firewall
      shell: daemon -- /home/ubuntu/run_snort.sh 
      ignore_errors: true


