---
- hosts: gateway      
  remote_user: ubuntu
  tasks:
    - name: update package registry
      apt: update_cache=yes 
      become: true  

    - apt: name=haproxy
      become: true
      
      #NOTE: Should not need to resolve to underlay IP if overlay's work properly
    - name: insert wordpress in hosts
      lineinfile: dest=/etc/hosts line="{{ webserver_ip }} wp"
      become: true 

    - name: copy haproxy script
      copy: src=haproxy.cfg dest=/home/ubuntu/haproxy.cfg

    - shell: haproxy -f /home/ubuntu/haproxy.cfg
      become: true
