---
- hosts: master
  remote_user: ubuntu
  tasks:
    - copy: src=~/.ssh/id_rsa dest=/home/ubuntu/.ssh/id_rsa mode=0600
    - copy: src=~/.ssh/id_rsa.pub dest=/home/ubuntu/.ssh/id_rsa.pub mode=0644

    - name: delete ext_ip file
      file : path=/home/ubuntu/vino_orc/ext_ip state=absent
      ignore_errors: true 

    - name: create ext_ip file
      file : path=/home/ubuntu/vino_orc/ext_ip mode=0777 state=touch
      
    - name: populate ext_ip file
      lineinfile: line={{master_ip}} state=present dest=/home/ubuntu/vino_orc/ext_ip

    - pause: seconds=10

    - name: copy edges.yaml
      synchronize: src=../../edges.yaml dest=/home/ubuntu/vino_orc

    - name: copy nodes.yaml
      synchronize: src=../../nodes.yaml dest=/home/ubuntu/vino_orc
    
    - name: download .tmux.conf
      get_url: dest=/home/ubuntu/.tmux.conf url=https://raw.githubusercontent.com/spandanb/utils/master/.tmux.conf

    - unarchive: src=portal.tar.gz dest=/home/ubuntu

    - name: install python packages
      shell: pip install django isodate
      become: true
      ignore_errors: true

    - name: create database 
      shell: mysql -uroot -pvinopass -e "CREATE DATABASE blade"
      ignore_errors: yes

    - name: copy master script
      copy: src=master-tmux.sh dest=/home/ubuntu/vino_orc/master-tmux.sh mode=0777

     #uses tmux instead of screen
#    - name: copy new screenrc file
#      copy: src=master-screenrc dest=/home/ubuntu/devstack/stack-screenrc

    - pause: seconds=15

    - name: run master script 
      shell: chdir=/home/ubuntu/vino_orc /home/ubuntu/vino_orc/master-tmux.sh
    
#    - name: run control stack in screen  
#      shell: chdir=/home/ubuntu/devstack ./rejoin-stack.sh
