---
- hosts: master
  remote_user: ubuntu
  tasks:
    - copy: src=~/.ssh/id_rsa dest=/home/ubuntu/.ssh/id_rsa mode=0600
    - copy: src=~/.ssh/id_rsa.pub dest=/home/ubuntu/.ssh/id_rsa.pub mode=0644

    - name: delete ext_ip file
      file : path=/home/ubuntu/vino_orc/ext_ip state=absent
      ignore_errors: true 

    - name: create ext_ip file
      file : path=/home/ubuntu/vino_orc/ext_ip mode=0777 state=touch
      
    - name: populate ext_ip file
      lineinfile: line={{master_ip}} state=present dest=/home/ubuntu/vino_orc/ext_ip

#    - name: write ext IP to file
#    - shell: echo {{master_ip}} > /home/ubuntu/vino_orc/ext_ip

    - name: copy nodes.yaml
      copy: src=../../nodes.yaml dest=/home/ubuntu/vino_orc
    
    - name: copy edges.yaml
      copy: src=../../edges.yaml dest=/home/ubuntu/vino_orc

    - pause: seconds=5

    - shell: screen -X -S stack quit
      ignore_errors: yes

    - pause: seconds=5

    - unarchive: src=portal.tar.gz dest=/home/ubuntu

    - copy: src=master-screenrc dest=/home/ubuntu/devstack/stack-screenrc
    
    - shell: pip install django isodate
      become: true
      ignore_errors: true

    - name: create database 
      shell: mysql -uroot -pvinopass -e "CREATE DATABASE blade"
      ignore_errors: yes

    - name: run control stack in screen  
      shell: chdir=/home/ubuntu/devstack ./rejoin-stack.sh
      async: 0
      poll: 0
      ignore_errors: true

